header_pages:

title: YugiQuery
author:
  name: Guilherme Ruiz
  email: 57478888+guigoruiz1@users.noreply.github.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This page was generated at <time datetime="{{ site.time | date_to_xmlschema }}">{{ site.time | date: "%d/%m/%Y %H:%M %Z" }}</time>
  
# Build settings

theme: minima

minima:
  skin: auto