title: YugiQuery

author:
  name: Guilherme Ruiz
  email: "guilherme.guigoruiz@gmail.com"

description: >
  Python script to query and display Yu-Gi-Oh! data built on Jupyter notebooks and Git.

show_excerpts: false

remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/guigoruiz1
    - title: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/guigoruiz1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-redirect-from

exclude:
  - assets
  - notebooks
  - yugiquery
  - docs
  - README.md
  - pyproject.toml
  - requirements.txt

header_pages:
  - repo_link.md