# header_pages:
#   - LICENSE.md

title: YugiQuery
author: 
  name: Guilherme Ruiz
  email: "guilherme.guigoruiz@gmail.com"

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Jupyter notebook to query and display yugipedia data.
  
# Build settings
show_excerpts: false

# theme: minima
remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
   - { platform: github,         user_url: "https://github.com/guigoruiz1/yugiquery" }
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme