header_pages: 
    - Cards.html
    - README.md
    - LICENSE.md

title: YugiQuery
author: Guilherme Ruiz
email: "57478888+guigoruiz1@users.noreply.github.com"

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Test
  
# Build settings
show_excerpts: false

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto