[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=4.1.2",]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# ...
# By default, include-package-data is true in pyproject.toml, so you do
# NOT have to specify this line.
include-package-data = true

[tool.setuptools.packages.find]
where = "."
exclude = ["tests", "wiki", "docs", "reports/yugiquery"]

[tool.setuptools_scm]
write_to = "yugiquery/metadata.py"
write_to_template = "__version__ = '{version}'\n"
version_scheme = "post-release"  # optional: defines how version numbers are generated
local_scheme = "dirty-tag"  # optional: handles local version identifiers for dirty repos

[project]
name = "yugiquery"
description = "A CLI tool for running Yugiquery tasks and bots."
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["CLI", "yugiquery", "bot", "Discord", "Telegram"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: Development"
]
dynamic = [
   "version"
]
requires-python = ">=3.11"

[project.urls]
"Homepage" = "https://guigoruiz1.github.io/yugiquery"
"Source" = "https://github.com/guigoruiz1/yugiquery"

[project.optional-dependencies]
docs = ["sphinx", "sphinx_rtd_theme"]
test = ["pytest", "coverage"]

[project.scripts]
yugiquery = "yugiquery.__main__:main"

[tool.coverage.run]
branch = true
source = ["yugiquery"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.mypy]
files = ["yugiquery"]
strict = true

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39']

[tool.isort]
profile = "black"